galaxy_info:
  author: Anton Karmanov
  description: Training db role for OTUS Reddit app
  company: null
  license: MIT
  min_ansible_version: 2.1

  platforms:
   - name: Ubuntu
     versions:
       - all

  galaxy_tags: []

dependencies: []
